name: Please Update the Translate
description: 通过这个模板进行催更
body:
  - type: markdown
    attributes:
      value: |
        我可能会没有时间检查原版是否更新，因此可能会忘记兼容新版汉化
  - type: textarea
    id: text
    attributes:
      label: 催更
      placeholder: "说些什么?"
    validations:
      required: true
